version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      args:
        - CHANGE_SOURCE=true
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ../PhpstormProjects:/var/www:cached
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=latest
    environment:
      - MYSQL_DATABASE=ledocker
      - MYSQL_USER=ledocker
      - MYSQL_PASSWORD=ledocker
      - MYSQL_ROOT_PASSWORD=root
      - TZ=UTC
    volumes:
      - ~/.ledocker/data/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "33066:3306"
    networks:
      - backend
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - CHANGE_SOURCE=true
        - PHP_VERSION=8.1
        - INSTALL_PHPREDIS=true
        - INSTALL_SWOOLE=false
        - INSTALL_AMQP=true
        - INSTALL_MONGO=true
        - INSTALL_INTL=true
        - PUID=1000
        - PGID=1000
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./php-fpm/php8.1.ini:/usr/local/etc/php/php.ini
      - ../PhpstormProjects:/var/www:cached
    expose:
      - "9000"  
    networks:
      - backend
  redis:
    build: ./redis
    volumes:
      - ~/.ledocker/data/redis:/data
    command: --requirepass ledocker
    ports:
      - "63799:6379"
    networks:
      - backend
networks:
  frontend:
    # driver: bridge
  backend:
    driver: bridge
volumes:
  mysql:
    driver: locale
